### PR TITLE
[Refactor] Refactor Form Input area

### PR DESCRIPTION
**Pull request by Chiranjibichapagain**
Remove outline and few other refactor.

### CODE REVIEW

**Review by Rostislav013 — APPROVED** [review]

**Review by MikeVedsted — CHANGES_REQUESTED** [review]
Please use mixins for styling. 
Also, you haven't solved 
1. the issue with resizing the field and the button going off screen.
2. the issue of the field not expanding if text exceeds the height

**Comment by Chiranjibichapagain** [comment]
> Please use mixins for styling.
> Also, you haven't solved
> 
> 1. the issue with resizing the field and the button going off screen.
> 2. the issue of the field not expanding if text exceeds the height

Fixed the text area height on the long text issue. But for resizing and  button issue I guess we fix it in the parent (commentInput) that you are working on.

**Comment by MikeVedsted** [comment]
> Fixed the text area height on the long text issue. But for resizing and button issue I guess we fix it in the parent (commentInput) that you are working on.

No, this has to be set in the textarea. To enable only vertial resizing, you can use `resize: vertical;` in the class for the input field itself

**Comment by Chiranjibichapagain** [comment]
> > Fixed the text area height on the long text issue. But for resizing and button issue I guess we fix it in the parent (commentInput) that you are working on.
> 
> No, this has to be set in the textarea. To enable only vertial resizing, you can use `resize: vertical;` in the class for the input field itself

But why do we need resizing in text box? i have a function that does it automatically. User don't have to do anything.

**Comment by MikeVedsted** [comment]
> > > Fixed the text area height on the long text issue. But for resizing and button issue I guess we fix it in the parent (commentInput) that you are working on.
> > 
> > 
> > No, this has to be set in the textarea. To enable only vertial resizing, you can use `resize: vertical;` in the class for the input field itself
> 
> But why do we need resizing in text box? i have a function that does it automatically. User don't have to do anything.

That is two different conversations. By setting `resize: vertical;` you prevent the button going off screen. I'm fine with setting the size automatically.

**Comment by Chiranjibichapagain** [comment]
> > > > Fixed the text area height on the long text issue. But for resizing and button issue I guess we fix it in the parent (commentInput) that you are working on.
> > > 
> > > 
> > > No, this has to be set in the textarea. To enable only vertial resizing, you can use `resize: vertical;` in the class for the input field itself
> > 
> > 
> > But why do we need resizing in text box? i have a function that does it automatically. User don't have to do anything.
> 
> That is two different conversations. By setting `resize: vertical;` you prevent the button going off screen. I'm fine with setting the size automatically.

I couldn't re create the problem; button going off the screen. Or maybe I didn't understand it.  But resize:vertical is in the  tetxarea's field now.

**Pull request merged**
