### PR TITLE
[refactor] Move icon library to its own file

### PR DESCRIPTION
**Pull request by Rostislav013**

### CODE REVIEW

**Review by MikeVedsted — APPROVED** [review]
Just se! 
Would it make sense to move it to helpers or up one level though, as it is not a constant file per se?

**Comment by Rostislav013** [comment]
> Just se!
> Would it make sense to move it to helpers or up one level though, as it is not a constant file per se?

Moved one lvl but not sure up or not heh

**Comment by MikeVedsted** [comment]
> Moved one lvl but not sure up or not heh
You did exactly what I meant, so perfect from my end

**Review by Chiranjibichapagain — APPROVED** [review]
:+1:

**Pull request merged**
